FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY requirements.service.txt .
RUN pip install --no-cache-dir -r requirements.service.txt
COPY app/service /app/service
EXPOSE 8000
CMD ["uvicorn","service.main:app","--host","0.0.0.0","--port","8000"]