name: Build & Push Docker (GHCR)


on:
  push:
    branches: ["main"]
    tags: ["v*"]


permissions:
  contents: read
  packages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    env:
    OWNER: ${{ github.repository_owner }}
    IMAGE_SERVICE: ghcr.io/${{ github.repository_owner }}/rag-service
    IMAGE_INGEST: ghcr.io/${{ github.repository_owner }}/rag-ingest
    steps:
      - uses: actions/checkout@v4


      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3

        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT || github.token }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT


      - name: Build & push SERVICE
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.service
          push: true
          tags: |
            ${{ env.IMAGE_SERVICE }}:latest
            ${{ env.IMAGE_SERVICE }}:${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Build & push INGEST
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ingest
          push: true
          tags: |
            ${{ env.IMAGE_INGEST }}:latest
            ${{ env.IMAGE_INGEST }}:${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max